version: '3'

services:
  database: #имя хоста
    image: mysql:latest
    #command: --default-authentication-plugin=mysql_native_password
    container_name: database #имя контейнера
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "9906:3306"

      

  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/apache2:/var/log/apache2
    links:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes: 
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
      - ./logs/nginx:/var/log/nginx
    links:
      - php-apache

volumes:
  db_volume:

