version: '3'


# Следует учитывать, что docker-composes работает с сервисами.
# 1 сервис = 1 контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
# Раздел, в котором будут описаны сервисы, начинается с 'services'.
services:
  database:
    image: mysql:latest
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      

  php-apache:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src/files:/var/www/html
    links:
      - database

volumes:
  db_volume:

